# Generated by Django 4.2.2 on 2023-06-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_blogpost_options_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(null=True, verbose_name='Publié'),
        ),
    ]
